sudo: required
services:
  - docker

before_install:
  - docker build -t apatil88/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run apatil88/react-test npm test -- --coverage

after_success:
  - docker build -t apatil88/multi-client ./client
  - docker build -t apatil88/multi-nginx ./nginx
  - docker build -t apatil88/multi-server ./server
  - docker build -t apatil88/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push apatil88/multi-client
  - docker push apatil88/multi-nginx
  - docker push apatil88/multi-server
  - docker push apatil88/multi-worker
